rails generate migration RemoveInning1FromMatch inning1_id:integer
rails generate migration RemoveInning2FromMatch inning2_id:integer
rails generate migration RemoveInning3FromMatch inning3_id:integer
rails generate migration RemoveInning4FromMatch inning4_id:integer

rails generate migration AddInningIdToMatch inning_id:integer

rails generate migration RemoveBattingPerformance1FromInning batting_performance1_id:inning
rails generate migration RemoveBattingPerformance2FromInning batting_performance2_id:inning
rails generate migration RemoveBattingPerformance3FromInning batting_performance3_id:inning
rails generate migration RemoveBattingPerformance4FromInning batting_performance4_id:inning
rails generate migration RemoveBattingPerformance5FromInning batting_performance5_id:inning
rails generate migration RemoveBattingPerformance6FromInning batting_performance6_id:inning
rails generate migration RemoveBattingPerformance7FromInning batting_performance7_id:inning
rails generate migration RemoveBattingPerformance8FromInning batting_performance8_id:inning
rails generate migration RemoveBattingPerformance9FromInning batting_performance9_id:inning
rails generate migration RemoveBattingPerformance10FromInning batting_performance10_id:inning
rails generate migration RemoveBattingPerformance11FromInning batting_performance11_id:inning

rails generate migration AddBattingIdPerformanceToInning batting_peformance_id:integer


rails generate migration RemoveBowlingPerformance1FromInning bowling_performance1_id:inning
rails generate migration RemoveBowlingPerformance2FromInning bowling_performance2_id:inning
rails generate migration RemoveBowlingPerformance3FromInning bowling_performance3_id:inning
rails generate migration RemoveBowlingPerformance4FromInning bowling_performance4_id:inning
rails generate migration RemoveBowlingPerformance5FromInning bowling_performance5_id:inning
rails generate migration RemoveBowlingPerformance6FromInning bowling_performance6_id:inning
rails generate migration RemoveBowlingPerformance7FromInning bowling_performance7_id:inning
rails generate migration RemoveBowlingPerformance8FromInning bowling_performance8_id:inning
rails generate migration RemoveBowlingPerformance9FromInning bowling_performance9_id:inning
rails generate migration RemoveBowlingPerformance10FromInning bowling_performance10_id:inning
rails generate migration RemoveBowlingPerformance11FromInning bowling_performance11_id:inning

rails generate migration AddBowlingPerformanceIdToInning batting_peformance_id:integer

