rails generate migration AddPlayer1IdToTeam player1_id:string
rails generate migration AddPlayer2IdToTeam player2_id:string
rails generate migration AddPlayer3IdToTeam player3_id:string
rails generate migration AddPlayer4IdToTeam player4_id:string
rails generate migration AddPlayer5IdToTeam player5_id:string
rails generate migration AddPlayer6IdToTeam player6_id:string
rails generate migration AddPlayer7IdToTeam player7_id:string
rails generate migration AddPlayer8IdToTeam player8_id:string
rails generate migration AddPlayer9IdToTeam player9_id:string
rails generate migration AddPlayer10IdToTeam player10_id:string
rails generate migration AddPlayer11IdToTeam player11_id:string
rails generate migration AddPlayer12IdToTeam player12_id:string
rails generate migration AddPlayer13IdToTeam player13_id:string
rails generate migration AddPlayer14IdToTeam player14_id:string
rails generate migration AddPlayer15IdToTeam player15_id:string
rails generate migration AddPlayer16IdToTeam player16_id:string
rails generate migration AddPlayer17IdToTeam player17_id:string
rails generate migration AddPlayer18IdToTeam player18_id:string
rails generate migration AddPlayer19IdToTeam player19_id:string
rails generate migration AddPlayer20IdToTeam player20_id:string
