class Inning < ActiveRecord::Base
	belongs_to :batting_performance1, :class_name => "BattingPerformance", :foreign_key => "batting_performance1_id"
	belongs_to :batting_performance2, :class_name => "BattingPerformance", :foreign_key => "batting_performance2_id"
	belongs_to :batting_performance3, :class_name => "BattingPerformance", :foreign_key => "batting_performance3_id"
	belongs_to :batting_performance4, :class_name => "BattingPerformance", :foreign_key => "batting_performance4_id"
	belongs_to :batting_performance5, :class_name => "BattingPerformance", :foreign_key => "batting_performance5_id"
	belongs_to :batting_performance6, :class_name => "BattingPerformance", :foreign_key => "batting_performance6_id"
	belongs_to :batting_performance7, :class_name => "BattingPerformance", :foreign_key => "batting_performance7_id"
	belongs_to :batting_performance8, :class_name => "BattingPerformance", :foreign_key => "batting_performance8_id"
	belongs_to :batting_performance9, :class_name => "BattingPerformance", :foreign_key => "batting_performance9_id"
	belongs_to :batting_performance10, :class_name => "BattingPerformance", :foreign_key => "batting_performance10_id"
	belongs_to :batting_performance11, :class_name => "BattingPerformance", :foreign_key => "batting_performance11_id"
	belongs_to :bowling_performance1, :class_name => "BowlingPerformance", :foreign_key => "bowling_performance1_id"
	belongs_to :bowling_performance2, :class_name => "BowlingPerformance", :foreign_key => "bowling_performance2_id"
	belongs_to :bowling_performance3, :class_name => "BowlingPerformance", :foreign_key => "bowling_performance3_id"
	belongs_to :bowling_performance4, :class_name => "BowlingPerformance", :foreign_key => "bowling_performance4_id"
	belongs_to :bowling_performance5, :class_name => "BowlingPerformance", :foreign_key => "bowling_performance5_id"
	belongs_to :bowling_performance6, :class_name => "BowlingPerformance", :foreign_key => "bowling_performance6_id"
	belongs_to :bowling_performance7, :class_name => "BowlingPerformance", :foreign_key => "bowling_performance7_id"
	belongs_to :bowling_performance8, :class_name => "BowlingPerformance", :foreign_key => "bowling_performance8_id"
	belongs_to :bowling_performance9, :class_name => "BowlingPerformance", :foreign_key => "bowling_performance9_id"
	belongs_to :bowling_performance10, :class_name => "BowlingPerformance", :foreign_key => "bowling_performance10_id"
	belongs_to :bowling_performance11, :class_name => "BowlingPerformance", :foreign_key => "bowling_performance11_id"
	has_one :match
end
